### ISSUE TITLE
Incorrect headshot for Kyle pitts in nflreadr::load_rosters()

### ISSUE THREAD

**Issue by SCasanova** [nflverse/nflfastR-roster#15]
As I understand it he shouldn't even have a headshot right now because he's a rookie. 

Anyway here's a reprex

``` r
library(magrittr)
nflreadr::load_rosters() %>% 
  dplyr::filter(full_name == 'Kyle Pitts') %>% 
  dplyr::pull(headshot_url)
#> [1] "https://a.espncdn.com/combiner/i?img=/i/headshots/nfl/players/full/15544.png" #Not Kyle Pitts
```

<sup>Created on 2021-08-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by SCasanova** [comment]
a headshot* not roster

**Comment by mrcaseb** [comment]
Uh oh. This means sleeper is providing the wrong espn_id for Kyle Pitts. Let's hope they fix their stuff. I will otherwise fix it manually before the regular season begins.

**Comment by tanho63** [comment]
ESPN doesn't have a headshot for Pitts yet to my knowledge https://www.espn.com/nfl/player/stats/_/id/4360248/kyle-pitts

perhaps will sort itself out soon

**Comment by mrcaseb** [comment]
Since sleeper is very slow with espn ids I have added a gsis headshot map of another source in #20 
This is resolved now
