### ISSUE TITLE
Depth Chart (and injury data?) with same week system like pbp

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflfastR-roster#18]
This has been posted in the nflverse discord

>> Hi Guys I have noticed with the depth chart dataset week numbers start again at 1 in the POST season and pbp weeks does not, can these vars be alignd [...]

I think that's probably a good idea @john-b-edwards?

**Comment by SingSing2020** [comment]
Thanks @mrcaseb and yes the injury data has another different week system (ends at week 17 with no season type var) pbp goes up to week 21 with playoff games

**Comment by john-b-edwards** [comment]
Makes total sense! I can tackle this later today.
