### ISSUE TITLE
Clarify weeks in depth charts

### ISSUE THREAD

**Issue by mrcaseb** [nflverse/nflfastR-roster#26]
This problem has been discussed here first https://github.com/nflverse/nflreadr/issues/78

I wrote some code to look at this and I think its a bit inconsistent

- week 18 is missing for <2006
- postseason is missing for 2005
- SB is week 22 for 2004, 2006, 2014
- week 20 mostly > week 19

``` r
library(dplyr, warn.conflicts = FALSE)
library(ggplot2)

df <- nflreadr::load_depth_charts(TRUE)

df |> 
  group_by(season, week, team) |> 
  summarise() |> 
  ungroup() |> 
  count(season, week) |> 
  mutate(alpha = ifelse(n == 32, 0.2, 1)) |> 
  ggplot(aes(x = season, y = week)) +
  geom_text(aes(label = n, alpha = alpha), size = 3) +
  scale_alpha_identity() +
  scale_y_continuous(breaks = scales::breaks_pretty(n = 10)) +
  theme_minimal()
```

![](https://i.imgur.com/lKoVcHY.png)

**Comment by mrcaseb** [comment]
We need to clarify season_type and week. 
Somewhere here?
https://github.com/nflverse/nflfastR-roster/blob/98e9d5283062138bc7806c49f495f2a10a90abc2/src/update-depth-charts.R#L73-L74

**Comment by john-b-edwards** [comment]
Me unmasking who wrote the code that caused this issue in the first place:

![](https://i.imgflip.com/4/3qf2u7.jpg)

**Comment by tanho63** [comment]
I think that looks better but we'll see when it runs a few more

**Comment by john-b-edwards** [comment]
Will try to hit this tonight or tomorrow and make sure this is 100% fixed
